# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Women Techmakers Vienna"
email: "team@womentechmakers.at"
description: "Women Techmakers Vienna is part of an international event series initiated by Google whose goal is to make women in tech more visible and to help build a better community."
baseurl: ""
url: "https://www.womentechmakers.at"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-21611117-7"
googleAnalyticsSiteUrl: "womentechmakers.at"
siteVerification: ""

# Organizer Info
organizerName: "GDG Vienna"
organizerAlternateName: "Google Developer Group Vienna"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "team@gdg-vienna.at"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.gdg-vienna.at/"

# Head
metaKeywords: "event, gdg, women in tech, google, programming, developers, vienna, austria"
twitterAccount: "@WTMvienna"
socialImageSrcGooglePlus: "/img/wtm-logo.png"
socialImageSrcTwitter: "/img/wtm-logo.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "/"
c4sponsorsUrl: "mailto:team@womentechmakers.at"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 # - {permalink: "/livestream/", text: "Livestream"}
 - {permalink: "/speakers/", text: "Speakers"}
 # - {permalink: "/call/", text: "Call for Speakers"}
 - {permalink: "/schedule/", text: "Schedule"}
 # - {permalink: "/kids-workshops/", text: "Kids' Workshop (2016)"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/recordings/", text: "Recordings"}
 - {permalink: "/photos/", text: "Photos"}
 # - {permalink: "/logistics/", text: "Logistics"}
 # - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 # - {link: "https://wtm-vienna-2018.eventbrite.com", text: "Register Now"}
 # - {permalink: "/call/", text: "Call for Speakers"}
 # - {permalink: "/livestream/", text: "Livestream"}
rightNavigationButtons:
 # - {link: "https://wtm-vienna-2018.eventbrite.com", text: "Register Now"}
 # - {permalink: "/call/", text: "Call for Speakers"}
 # - {permalink: "/livestream/", text: "Livestream"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Women Techmakers Vienna"
heroSubtitle: "9 March 2019"
eventDate: "9 March 2019"
eventDateISO: "2019-03-09T09:30+01:00"
# typeoutTextValues: '"", "2014", "2015"'
# typeoutFallback: "2015"
heroButtons:
 # - {link: "https://wtm-vienna-2018.eventbrite.com", text: "Register Now"}
 # - {permalink: "/call/", text: "Call for Speakers"}
 # - {permalink: "/livestream/", text: "Livestream"}

# About Block
aboutTitle: "About Women Techmakers Vienna"
aboutInfo: "People of all genders are welcome to attend our event.<br>As always, we try to focus on the accomplishments of technologists that also happen to be women, rather than just focusing on the story of doing something as a woman. This helps the focus be more of the work rather than our gender.<br>We aim to keep things positive when selecting panels, talks, keynotes, etc. We know that we need more women in tech and there are issues we face in the industry, but one of the most powerful things we can do to counter act that is to show the women doing great things and what we are achieving.<br>"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "Supporting women in tech through the power of example." }
 - {title: "Workshops", image: "workshop.jpg", text: "High-tech workshops, hands-on experience, hacking and debugging. Delivered by top women in tech!" }
 - {title: "Discussion", image: "discussion.jpg", text: "How can we close the gender gap in science, tech, engineering & mathematics? On-stage panel discussion with experts and leaders." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "attendees", detail: "from everywhere - men &amp; women"}
 - {count: "8", specialCharacter: "+", info: "hours", detail: "sessions, workshops &amp; discussion"}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: "local professionals"}
 # - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest News"

# Strategy Block
strategyTitle: "What we stand for"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 1
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "TU Wien, Domed Hall (Kuppelsaal)"
eventLocationLink: "http://www.tuwien.ac.at"
eventStreetAddress: "Karlsplatz 13, 1040 Wien"
eventAddressLocality: "Vienna"
eventAddressLocalityRegion: "Vienna"
eventPostalCode: "1040"
eventAddressCountry: "Austria"
eventStartTime: "2019-03-09T10:00"
eventDoorTime: "09:00"
eventEndTime: "2019-03-09T19:00"
eventPlaceCoordinates: "48.1989203,16.369706"
mapCenterCoordinates: "48.1989203,16.369706"
mapMobileCenterCoordinates: "48.1989203,16.369706"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Venue Location"
venueFeatures: ["What to say", "about the location", "where it is"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "wtmvie19"
twitterFeed: "/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a Sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://subscribe-for-updates.at"
subscribeInfo: "Registration will be open around end of January. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "10"
  priceCurrency: "EUR"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "12"
  priceCurrency: "EUR"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+WomentechmakersAt", icon: "google-plus"}
 - {link: "https://twitter.com/WTMVienna", icon: "twitter"}
 - {link: "https://www.facebook.com/WomenTechmakersVienna", icon: "facebook"}
 # - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.gdg-vienna.at", text: "GDG Vienna"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:team@womentechmakers.at", text: "team@womentechmakers.at"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}
 -
  title: "Social Links"
  links:
   - {link: "https://plus.google.com/+WomentechmakersAt", text: "Google+"}
   - {link: "https://twitter.com/WTMVienna", text: "Twitter"}
   - {link: "https://www.facebook.com/WomenTechmakersVienna", text: "Facebook"}
   # - {permalink: "/feed.xml", icon: "rss"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "wtmvienna"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "The core team of Women Techmakers Vienna 2019 consists of enthusiastic volunteers that are trying to make a difference in the world of STEM. The core team has different responsibilities and together with the support of collaborators (also volunteers) and sponsors we are working on making Women Techmakers Vienna 2019 an event where everyone is welcome and we can reach fruitful outcomes together."

#Workshop for kids Block
kidsWStitel: "Learn Game programming by using Scratch"

# location of thumbnails
thumbnailsFolder: /img/people/
thumbnailsSessions: /img/sessions/
thumbnailsPhotos: /photos/thumbnails/
photosFolder: /photos/large/

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "48.1964423,16.369645"
logisticsMapMobileCenterCoordinates: "48.1964423,16.369645"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Vienna"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"

collections:
  strategy:
    output: true
